apiVersion: apps/v1
kind: Deployment
metadata:
  name: audiobookshelf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: audiobookshelf
  template:
    metadata:
      labels:
        app: audiobookshelf
#    spec:
#      securityContext:
#        runAsNonRoot: true
#        runAsUser: 33
#        runAsGroup: 33
#        fsGroup: 33
      containers:
        - name: audiobookshelf
          image: ghcr.io/advplyr/audiobookshelf:2.32.*
#          securityContext:
#            allowPrivilegeEscalation: false
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: audiobookshelf-configmap
                  key: PORT
          ports:
            - containerPort: 3005
          volumeMounts:
            - name: app-volume
              mountPath: /config
              subPath: config
            - name: app-volume
              mountPath: /audiobooks
              subPath: audiobooks
            - name: app-volume
              mountPath: /podcasts
              subPath: podcasts
            - name: app-volume
              mountPath: /metadata
              subPath: metadata

      volumes:
        - name: app-volume
          persistentVolumeClaim:
            claimName: audiobookshelf-pvc
